### ISSUE TITLE
[1.12-2.1.2] Crash when opening Pulvus

### ISSUE THREAD

**Issue by tetious** [KidsDontPlay/Furnus#32]
I get a repeatable client crash every time I try to open a newly placed pulvus. Probably some mod conflict, but I'm not sure which. :)

MC: 1.12.1
Forge: 1.12.1-14.22.1.2485
Furnus: 1.12-2.1.2

```
Description: Ticking screen

java.lang.NoSuchFieldError: stack
	at mrriegel.furnus.gui.GuiDevice.func_73876_c(GuiDevice.java:155)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1777)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

https://gist.github.com/tetious/67659a0ae48972e06ef3a1a5dc05e0a1

**Comment by KidsDontPlay** [comment]
probably an incompatibility with latest limelib.

[furnus-1.12.2-2.1.2xxx.zip](https://github.com/MrRiegel/Furnus/files/1347559/furnus-1.12.2-2.1.2xxx.zip)

try this one. rename the file extension to `jar` and test it

**Comment by tetious** [comment]
It works perfectly with the new version. THANKS!
