### ISSUE TITLE
DIsabling RF Upgrades causes crash

### ISSUE THREAD

**Issue by dredhorse** [KidsDontPlay/Furnus#40]
Hi,

I disabled the RF Upgrade and get the following in the log:

[13:32:01] [main/ERROR] [jei]: Recipe has no output. Furnus furnus:upgrade|6#1_2691
Outputs:
net.minecraft.item.ItemStack: [[]]
Inputs:
net.minecraft.item.ItemStack: [[], [1xitem.yellowDust@0 minecraft:glowstone_dust], [], [1xtile.blockRedstone@0 minecraft:redstone_block, 1xtile.chisel.redstone@0 chisel:redstone, 1xtile.chisel.redstone@1 chisel:redstone, 1xtile.chisel.redstone@2 chisel:redstone, 1xtile.chisel.redstone@3 chisel:redstone, 1xtile.chisel.redstone@4 chisel:redstone, 1xtile.chisel.redstone@5 chisel:redstone, 1xtile.chisel.redstone@6 chisel:redstone, 1xtile.chisel.redstone@7 chisel:redstone, 1xtile.chisel.redstone@8 chisel:redstone, 1xtile.chisel.redstone@9 chisel:redstone, 1xtile.chisel.redstone@10 chisel:redstone, 1xtile.chisel.redstone@11 chisel:redstone, 1xtile.chisel.redstone@12 chisel:redstone, 1xtile.chisel.redstone@13 chisel:redstone, 1xtile.chisel.redstone@14 chisel:redstone, 1xtile.chisel.redstone@15 chisel:redstone, 1xtile.chisel.redstone@0 chisel:redstone1, 1xtile.chisel.redstone@1 chisel:redstone1, 1xtile.chisel.redstone@2 chisel:redstone1, 1xtile.chisel.redstone@3 chisel:redstone1, 1xtile.chisel.redstone@4 chisel:redstone1, 1xtile.chisel.redstone@5 chisel:redstone1, 1xtile.chisel.redstone@6 chisel:redstone1, 1xtile.chisel.redstone@7 chisel:redstone1, 1xtile.chisel.redstone@8 chisel:redstone1, 1xtile.chisel.redstone@9 chisel:redstone1, 1xtile.chisel.redstone@10 chisel:redstone1, 1xtile.chisel.redstone@11 chisel:redstone1], [1xitem.ingotIron@0 minecraft:iron_ingot], [1xtile.blockRedstone@0 minecraft:redstone_block, 1xtile.chisel.redstone@0 chisel:redstone, 1xtile.chisel.redstone@1 chisel:redstone, 1xtile.chisel.redstone@2 chisel:redstone, 1xtile.chisel.redstone@3 chisel:redstone, 1xtile.chisel.redstone@4 chisel:redstone, 1xtile.chisel.redstone@5 chisel:redstone, 1xtile.chisel.redstone@6 chisel:redstone, 1xtile.chisel.redstone@7 chisel:redstone, 1xtile.chisel.redstone@8 chisel:redstone, 1xtile.chisel.redstone@9 chisel:redstone, 1xtile.chisel.redstone@10 chisel:redstone, 1xtile.chisel.redstone@11 chisel:redstone, 1xtile.chisel.redstone@12 chisel:redstone, 1xtile.chisel.redstone@13 chisel:redstone, 1xtile.chisel.redstone@14 chisel:redstone, 1xtile.chisel.redstone@15 chisel:redstone, 1xtile.chisel.redstone@0 chisel:redstone1, 1xtile.chisel.redstone@1 chisel:redstone1, 1xtile.chisel.redstone@2 chisel:redstone1, 1xtile.chisel.redstone@3 chisel:redstone1, 1xtile.chisel.redstone@4 chisel:redstone1, 1xtile.chisel.redstone@5 chisel:redstone1, 1xtile.chisel.redstone@6 chisel:redstone1, 1xtile.chisel.redstone@7 chisel:redstone1, 1xtile.chisel.redstone@8 chisel:redstone1, 1xtile.chisel.redstone@9 chisel:redstone1, 1xtile.chisel.redstone@10 chisel:redstone1, 1xtile.chisel.redstone@11 chisel:redstone1], [], [1xitem.ingotGold@0 minecraft:gold_ingot], []]

Which isn't something really problematic, but Better Questing causes a crash 

`java.lang.RuntimeException: Item "furnus:upgrade" (mrriegel.furnus.item.ItemUpgrade) threw a fatal error during search! Please report this to the item's developer(s).
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.updateSearch(CanvasItemDatabase.java:159)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.drawPanel(CanvasItemDatabase.java:64)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
	at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:186)
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73863_a(GuiScreenCanvas.java:112)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Invalid item stack "0xtile.air@6" registed to creative search tab!
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.updateSearch(CanvasItemDatabase.java:125)
	... 17 more
`
[crash-2018-10-09_13.29.03-client.txt](https://github.com/MrRiegel/Furnus/files/2460235/crash-2018-10-09_13.29.03-client.txt)

**Comment by dredhorse** [comment]
that was fast, thanks :-)
